imagePath: '壁紙に設定する画像ファイルを含むディレクトリをフルパスで指定'
rectangleList:
  -
    x: 0
    y: 0
    width: 1920
    height: 1080
  -
    x: 1920
    y: 0
    width: 1920
    height: 1080
  -
    x: 3840
    y: 0
    width: 1920
    height: 1080
  -
    x: 0
    y: 1080
    width: 1920
    height: 1080
  -
    x: 1920
    y: 1080
    width: 1920
    height: 1080
  -
    x: 3840
    y: 1080
    width: 1920
    height: 1080
