[build]
target-dir = "./target"

[alias]
ws-build = "build --manifest-path ./workspace-rust/Cargo.toml"
ws-clean = "clean --manifest-path ./workspace-rust/Cargo.toml"
ws-fmt = "fmt --manifest-path ./workspace-rust/Cargo.toml"

[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-args=/OPT:REF,ICF",
  "-C", "link-args=/LTCG",
  "-C", "target-feature=+avx2"
]
