name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag format is Semver, input "vX.Y.Z"
        required: true
        type: string
      
jobs:
  build:
    if: ${{ github.event.inputs.tag }} =~ ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-files: 'go.mod'
    - name: Build
      shell: powershell
      run: |
        go install github.com/google/go-licenses@latest
        go-licenses save ./... --force --save_path build/WallpaperChanger/licenses
        go build -o build/WallpaperChanger/ConfigCreater.exe -ldflags "-s -w -X=github.com/ryo-kagawa/WallpaperChanger/subcommand.name=ConfigCreater.exe -X=github.com/ryo-kagawa/WallpaperChanger/subcommand.version=${{ github.event.inputs.tag }}" -trimpath ./cmd/config-creater
        go build -o build/WallpaperChanger/WallpaperChanger.exe -ldflags "-s -w -H=windowsgui -X=github.com/ryo-kagawa/WallpaperChanger/subcommand.name=WallpaperChanger.exe -X=github.com/ryo-kagawa/WallpaperChanger/subcommand.version=${{ github.event.inputs.tag }}" -trimpath ./cmd/wallpaper-changer
        go build -o build/WallpaperChanger/WallpaperRegistry.exe -ldflags "-s -w -X=github.com/ryo-kagawa/WallpaperChanger/subcommand.name=WallpaperRegistry.exe -X=github.com/ryo-kagawa/WallpaperChanger/subcommand.version=${{ github.event.inputs.tag }}" -trimpath ./cmd/wallpaper-registry
        COPY README-windows.txt build\WallpaperChanger\README.txt
        Compress-Archive -Path build\WallpaperChanger\* -Destination build\WallpaperChanger_${{ github.event.inputs.tag }}.zip
    - name: GitHub Release
      run: |
        gh release create ${{ github.event.inputs.tag }} build\WallpaperChanger_${{ github.event.inputs.tag }}.zip --draft --generate-notes --title ${{ github.event.inputs.tag }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
